/* SPDX-License-Identifier: Unlicense */
#include "vibesolaris.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <dirent.h>
#include <sys/stat.h>
#include <unistd.h>

static void gcopy(char *d,size_t cap,const char *s){size_t n;if(!d||cap==0)return;if(!s)s="";n=strlen(s);if(n>=cap)n=cap-1;memcpy(d,s,n);d[n]=0;}
static int skip_dir(const char *n){static const char *x[]={".git",".hg",".svn","node_modules","target","dist","build","out",".idea",".vscode","__pycache__",".gradle",0};int i;for(i=0;x[i];i++)if(!strcmp(n,x[i]))return 1;return 0;}
static int graph_file_ext(const char *p){const char *e=strrchr(p,'.');if(!e)return 0;e++;return !strcmp(e,"c")||!strcmp(e,"h")||!strcmp(e,"cc")||!strcmp(e,"cpp")||!strcmp(e,"cxx")||!strcmp(e,"hpp")||!strcmp(e,"java")||!strcmp(e,"py")||!strcmp(e,"rs")||!strcmp(e,"go")||!strcmp(e,"js")||!strcmp(e,"jsx")||!strcmp(e,"ts")||!strcmp(e,"tsx")||!strcmp(e,"md")||!strcmp(e,"markdown")||!strcmp(e,"sh")||!strcmp(e,"xml")||!strcmp(e,"json")||!strcmp(e,"toml")||!strcmp(e,"yaml")||!strcmp(e,"yml")||!strcmp(e,"gradle");}
static const char *base_name(const char *p){const char *s=strrchr(p,'/');return s?s+1:p;}
static int join(char *o,size_t cap,const char *a,const char *b){size_t n;if(!a||!b)return -1;n=strlen(a);if(n+strlen(b)+2>cap)return -1;strcpy(o,a);if(n&&o[n-1]!='/')strcat(o,"/");strcat(o,b);return 0;}
static int add_node(VSGraph *g,const char *label,const char *path,int kind){int i;if(!g)return -1;for(i=0;i<g->node_count;i++){if(kind==1&&path&&*path&&!strcmp(g->nodes[i].path,path))return i;if(kind!=1&&label&&path&&!strcmp(g->nodes[i].label,label)&&!strcmp(g->nodes[i].path,path))return i;}if(g->node_count>=VS_GRAPH_MAX_NODES){g->truncated=1;return -1;}i=g->node_count++;memset(&g->nodes[i],0,sizeof(g->nodes[i]));gcopy(g->nodes[i].label,sizeof(g->nodes[i].label),label&&*label?label:"?");gcopy(g->nodes[i].path,sizeof(g->nodes[i].path),path?path:"");g->nodes[i].kind=kind;g->nodes[i].weight=1;return i;}
static void add_edge(VSGraph *g,int from,int to){int i;if(!g||from<0||to<0||from==to)return;for(i=0;i<g->edge_count;i++)if(g->edges[i].from==(unsigned short)from&&g->edges[i].to==(unsigned short)to)return;if(g->edge_count>=VS_GRAPH_MAX_EDGES){g->truncated=1;return;}g->edges[g->edge_count].from=(unsigned short)from;g->edges[g->edge_count].to=(unsigned short)to;g->edge_count++;g->nodes[from].weight++;g->nodes[to].weight++;}
static void scan_files(VSContext *ctx,const char *root,const char *path,VSGraph *g,int depth){DIR *d;struct dirent *de;struct stat st;char full[VS_MAX_PATH],rel[VS_GRAPH_PATH_MAX];if(depth>18||g->node_count>=VS_GRAPH_MAX_NODES||vs_cancel_requested(ctx))return;d=opendir(path);if(!d)return;while((de=readdir(d))!=NULL){if(!strcmp(de->d_name,".")||!strcmp(de->d_name,".."))continue;if(join(full,sizeof(full),path,de->d_name)!=0)continue;if(lstat(full,&st)!=0)continue;if(S_ISDIR(st.st_mode)){if(!skip_dir(de->d_name))scan_files(ctx,root,full,g,depth+1);}else if(S_ISREG(st.st_mode)&&graph_file_ext(full)){const char *rp=full;if(!strncmp(full,root,strlen(root))){rp=full+strlen(root);if(*rp=='/')rp++;}gcopy(rel,sizeof(rel),rp);add_node(g,base_name(rel),rel,1);}if(g->node_count>=VS_GRAPH_MAX_NODES||vs_cancel_requested(ctx))break;}closedir(d);}
static int path_suffix_match(const char *path,const char *ref){size_t a,b;if(!path||!ref)return 0;a=strlen(path);b=strlen(ref);if(a<b)return 0;if(strcmp(path+a-b,ref))return 0;return a==b||path[a-b-1]=='/';}
static void clean_ref(char *s){char *p=s;size_t n;while(*p&&isspace((unsigned char)*p))p++;if(p!=s)memmove(s,p,strlen(p)+1);n=strlen(s);while(n&&(isspace((unsigned char)s[n-1])||s[n-1]=='"'||s[n-1]=='\''||s[n-1]==')'||s[n-1]==';'))s[--n]=0;while(*s=='"'||*s=='\''||*s=='<'||*s=='(')memmove(s,s+1,strlen(s));}
static int find_ref_node(const VSGraph *g,const char *ref){int i,only=-1,count=0;char r[VS_GRAPH_PATH_MAX];const char *bn;if(!ref||!*ref)return -1;gcopy(r,sizeof(r),ref);clean_ref(r);while(!strncmp(r,"./",2))memmove(r,r+2,strlen(r)-1);for(i=0;i<g->node_count;i++)if(!strcmp(g->nodes[i].path,r)||path_suffix_match(g->nodes[i].path,r))return i;bn=base_name(r);for(i=0;i<g->node_count;i++)if(!strcmp(base_name(g->nodes[i].path),bn)){only=i;count++;}return count==1?only:-1;}
static int extract_quoted(const char *line,char *out,size_t cap){const char *a,*b;a=strchr(line,'"');if(!a)a=strchr(line,'\'');if(!a)return 0;b=strchr(a+1,*a);if(!b)return 0;{size_t n=(size_t)(b-a-1);if(n>=cap)n=cap-1;memcpy(out,a+1,n);out[n]=0;}return 1;}
static void build_file_edges(VSContext *ctx,const char *root,VSGraph *g){int i,j;char full[VS_MAX_PATH],line[4096],ref[VS_GRAPH_PATH_MAX];FILE *f;for(i=0;i<g->node_count;i++){if(join(full,sizeof(full),root,g->nodes[i].path)!=0)continue;f=fopen(full,"rb");if(!f)continue;for(j=0;j<5000&&fgets(line,sizeof(line),f);j++){char *p=line;while(*p&&isspace((unsigned char)*p))p++;ref[0]=0;if(!strncmp(p,"#include",8)&&extract_quoted(p,ref,sizeof(ref))){int to=find_ref_node(g,ref);if(to>=0)add_edge(g,i,to);}else if((strstr(p,"import ")||strstr(p,"require(")||strstr(p," from "))&&extract_quoted(p,ref,sizeof(ref))){int to=find_ref_node(g,ref);if(to<0&&strchr(ref,'.')==NULL){char r2[VS_GRAPH_PATH_MAX];size_t rn=strlen(ref);if(rn+4<=sizeof(r2)){memcpy(r2,ref,rn);memcpy(r2+rn,".js",4);to=find_ref_node(g,r2);if(to<0){memcpy(r2+rn,".ts",4);to=find_ref_node(g,r2);}}}if(to>=0)add_edge(g,i,to);}else if(strstr(p,"](")!=NULL){char *a=strstr(p,"](");char *b;if(a){a+=2;b=strchr(a,')');if(b&&(size_t)(b-a)<sizeof(ref)){memcpy(ref,a,(size_t)(b-a));ref[b-a]=0;if(ref[0]!='#'&&strstr(ref,"://")==NULL){int to=find_ref_node(g,ref);if(to>=0)add_edge(g,i,to);}}}}else if(strstr(p,"[[")!=NULL){char *a=strstr(p,"[["),*b;if(a){a+=2;b=strstr(a,"]]" );if(b&&(size_t)(b-a)<sizeof(ref)){memcpy(ref,a,(size_t)(b-a));ref[b-a]=0;{char *bar=strchr(ref,'|');if(bar)*bar=0;} {int to=find_ref_node(g,ref);if(to>=0)add_edge(g,i,to);}}}}if(vs_cancel_requested(ctx))break;}fclose(f);if(vs_cancel_requested(ctx))break;}}
static int c_source_path(const char *p){const char *e=strrchr(p,'.');if(!e)return 0;e++;return !strcmp(e,"c")||!strcmp(e,"h")||!strcmp(e,"cc")||!strcmp(e,"cpp")||!strcmp(e,"cxx")||!strcmp(e,"hpp");}
static void ident_before_semicolon(const char *line,char *out,size_t cap){const char *semi=strchr(line,';'),*p,*e;size_t n;out[0]=0;if(!semi||strchr(line,'('))return;p=semi;while(p>line&&(isspace((unsigned char)p[-1])||p[-1]==']'||isdigit((unsigned char)p[-1])))p--;while(p>line&&p[-1]=='['){while(p>line&&p[-1]!=' ')p--;}e=p;while(p>line&&(isalnum((unsigned char)p[-1])||p[-1]=='_'))p--;n=(size_t)(e-p);if(n==0||n>=cap)return;memcpy(out,p,n);out[n]=0;}
static void build_field_graph(VSContext *ctx,const char *root,VSGraph *files,VSGraph *out){int i;char full[VS_MAX_PATH],line[4096],sname[128],field[128],tmpname[128];FILE *f;int in_struct=0,parent=-1,anon=0,lineno=0,child_start=0;for(i=0;i<files->node_count;i++){if(!c_source_path(files->nodes[i].path))continue;if(join(full,sizeof(full),root,files->nodes[i].path)!=0)continue;f=fopen(full,"rb");if(!f)continue;in_struct=0;parent=-1;anon=0;lineno=0;while(fgets(line,sizeof(line),f)){char *p=line,*brace,*end;lineno++;while(*p&&isspace((unsigned char)*p))p++;if(!in_struct){if((!strncmp(p,"typedef struct",14)||!strncmp(p,"struct ",7))&&(brace=strchr(p,'{'))!=NULL){const char *q=strstr(p,"struct");q=q?q+6:p;while(*q&&isspace((unsigned char)*q))q++;sname[0]=0;if(q<brace){size_t n=0;while(q+n<brace&&(isalnum((unsigned char)q[n])||q[n]=='_'))n++;if(n>0&&n<sizeof(sname)){memcpy(sname,q,n);sname[n]=0;}}anon=sname[0]?0:1;if(anon)snprintf(sname,sizeof(sname),"struct@%s:%d",base_name(files->nodes[i].path),lineno);parent=add_node(out,sname,files->nodes[i].path,2);child_start=out->node_count;in_struct=1;continue;}}else{if((end=strchr(p,'}'))!=NULL){if(anon){char *q=end+1;size_t n=0;while(*q&&isspace((unsigned char)*q))q++;while(isalnum((unsigned char)q[n])||q[n]=='_')n++;if(n>0&&n<sizeof(tmpname)){int k;memcpy(tmpname,q,n);tmpname[n]=0;gcopy(out->nodes[parent].label,sizeof(out->nodes[parent].label),tmpname);for(k=child_start;k<out->node_count;k++){char *dot=strchr(out->nodes[k].label,'.');if(dot){char suffix[96];gcopy(suffix,sizeof(suffix),dot);snprintf(out->nodes[k].label,sizeof(out->nodes[k].label),"%.70s%.55s",tmpname,suffix);}}}}in_struct=0;parent=-1;continue;}ident_before_semicolon(p,field,sizeof(field));if(field[0]&&parent>=0){char lbl[VS_GRAPH_LABEL_MAX];int fn;snprintf(lbl,sizeof(lbl),"%.70s.%.50s",out->nodes[parent].label,field);fn=add_node(out,lbl,files->nodes[i].path,3);if(fn>=0)add_edge(out,parent,fn);}}if(out->node_count>=VS_GRAPH_MAX_NODES||vs_cancel_requested(ctx))break;}fclose(f);if(out->node_count>=VS_GRAPH_MAX_NODES||vs_cancel_requested(ctx))break;}}

int vs_graph_build(VSContext *ctx,const char *root,VSGraphMode mode,VSGraph *out){VSGraph files;char absroot[VS_MAX_PATH];if(!out)return -1;memset(out,0,sizeof(*out));memset(&files,0,sizeof(files));if(!root||!*root)root=(ctx&&ctx->cwd[0])?ctx->cwd:".";gcopy(absroot,sizeof(absroot),root);out->mode=mode;gcopy(out->root,sizeof(out->root),absroot);if(mode==VS_GRAPH_FILES){scan_files(ctx,absroot,absroot,out,0);build_file_edges(ctx,absroot,out);return out->node_count;}files.mode=VS_GRAPH_FILES;gcopy(files.root,sizeof(files.root),absroot);scan_files(ctx,absroot,absroot,&files,0);build_field_graph(ctx,absroot,&files,out);return out->node_count;}

char *vs_graph_summary(const VSGraph *g,int max_lines){size_t cap=65536,n=0;char *o;int i,shown;if(!g)return NULL;if(max_lines<8)max_lines=8;if(max_lines>500)max_lines=500;o=(char*)malloc(cap);if(!o)return NULL;n+=(size_t)snprintf(o+n,cap-n,"%s graph: %d nodes, %d edges%s\nroot: %s\n",g->mode==VS_GRAPH_FIELDS?"Field":"File",g->node_count,g->edge_count,g->truncated?" (truncated)":"",g->root);shown=0;for(i=0;i<g->node_count&&shown<max_lines/2&&n<cap-256;i++,shown++)n+=(size_t)snprintf(o+n,cap-n,"  [%d] %s%s%s\n",i,g->nodes[i].label,g->nodes[i].path[0]?"  -  ":"",g->nodes[i].path);shown=0;for(i=0;i<g->edge_count&&shown<max_lines/2&&n<cap-256;i++,shown++){int a=g->edges[i].from,b=g->edges[i].to;n+=(size_t)snprintf(o+n,cap-n,"  %s -> %s\n",g->nodes[a].label,g->nodes[b].label);}if(i<g->edge_count&&n<cap-128)snprintf(o+n,cap-n,"  ... %d more edges ...\n",g->edge_count-i);return o;}
static void dot_escape(FILE *f,const char *s){for(;s&&*s;s++){if(*s=='"'||*s=='\\')fputc('\\',f);if(*s=='\n'||*s=='\r')fputc(' ',f);else fputc(*s,f);}}
int vs_graph_export_dot(const VSGraph *g,const char *path){FILE *f;int i;if(!g||!path||!*path)return -1;f=fopen(path,"wb");if(!f)return -1;fprintf(f,"digraph vibesolaris {\n  graph [overlap=false, splines=true];\n  node [shape=box, fontsize=10];\n");for(i=0;i<g->node_count;i++){fprintf(f,"  n%d [label=\"",i);dot_escape(f,g->nodes[i].label);fprintf(f,"\"];\n");}for(i=0;i<g->edge_count;i++)fprintf(f,"  n%u -> n%u;\n",(unsigned)g->edges[i].from,(unsigned)g->edges[i].to);fprintf(f,"}\n");fclose(f);return 0;}
